recorded_path_file : "/home/ruthz/Desktop/pathnew.txt"
Q_matrix_diag : "160.0, 160.0 ,200.0"
R_matrix_diag : "3000.0, 3000.0"
state_dimension_length : "3"
input_dimension_length : "2"
sampling_period : "3"
time_window : "15"