recorded_path_file : "/home/ruthz/udacity_ws/src/udacity_proj/udacity_proj_pkg/path/ramp_path.txt"
Q_matrix_diag : "300.0, 300.0 ,200.0"
R_matrix_diag : "3000.0, 3000.0"
state_dimension_length : "3"
input_dimension_length : "2"
sampling_period : "2"
time_window : "22"