recorded_path_file : "/home/ruthz/Desktop/path.txt"
Q_matrix_diag : "160.0, 160.0 ,200.0"
R_matrix_diag : "3000.0, 3000.0"
recorded_path_file: "/home/catkin_ws/src/udacity_proj/udacity_proj_pkg/config/path.txt"
state_dimension_length : "3"
input_dimension_length : "2"
sampling_period : "3"
time_window : "15"